apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-kafka-app.fullname" . }}-secret
  labels:
    {{- include "flask-kafka-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_USERNAME: {{ .Values.secrets.KAFKA_USERNAME | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.KAFKA_PASSWORD | quote }}
